# Generated by Django 2.0.3 on 2018-03-28 19:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='date_a',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 28, 19, 31, 54, 55595, tzinfo=utc)),
        ),
    ]
